### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by RumisPoint** [Nauplius/FoundationSync#3]
Per forum discussion https://social.technet.microsoft.com/Forums/office/en-US/9708fd4a-7681-4afe-84ad-45842c39645a/ad-synchronization-sharepoint-foundation?forum=sharepointadminprevious, I'd like to request the following features added to the FoundationSync solution:

1.  Remove users from SharePoint if they are either disabled or deleted from AD
2.  Incorporate reporting capability such as:
xxxxx total users found in 1 site collection(s).
xxx total orphaned accounts deleted from SharePoint.
xxx total orphaned accounts found.
xxxx total users with updated properties (possibly what properties were updated)
x total errors encountered 
3.  Can the timer job be granular so it can be run against specific web/apps, site collections?  
4.  Does this put a large load on the servers when dealing with large user base?

Thank you,

Rumi

**Comment by tseward** [comment]
To answer question #4, it does enumerate through all SPUser objects in a Site Collection (much like the script you mentioned would). I've never profiled the memory usage, but all objects are being properly disposed. I do set the job to run in the early AM hours to avoid business hours (and of course you can freely adjust the schedule).

Thanks for the feature requests, They should be doable, although how do you envision what #2 would look like? My thought is just to throw the numbers into the ULS log and you can parse it out from there. Event Logging is out as creating a new source requires Local Admin rights, and I want to avoid doing that.

**Comment by RumisPoint** [comment]
Trevor:
Thank you for acknowledging this.  So, I could potentially dedicate one server in my farm to take care of this job, couldn't I?  As for my scripts, I have actually added one server to the far (because it has to be part of the farm) and all the PowerShell scripts for the ADSynch are running from this one server.

And for #2, is there anyway it the job can output to a file either on the file system or to a document library?  

Thank you,

Rumi

**Comment by tseward** [comment]
The LockType on this is Job, which means any SharePoint server that is available will pick up the job.

I'll take a look at the output options. The only restriction here is that the Farm Admin (owstimer) account would need write access. Since the LockType is job, the File System location would need to be present on all servers in the farm -- so that may not be a good option. Creating a reporting library in Central Admin would be fairly easy as the Farm Admin account does have access there. While you generally don't want to put content in CA, other services such as PowerPivot do so. Would that be acceptable?

**Comment by RumisPoint** [comment]
"The LockType on this is Job" - I see.  So, there is no way around it?  For instance, one could have a "preferred server for timer jobs" for a particular content DB.  I am wondering if something like that can be done for this?

Maybe I'm looking at this too simplistic, but why would it not be a good option if the file system location needs to be present on all server?  That's how we setup diagnostic logging on the farm.  We could simply give the farm admin account write access to that location.

But, a reporting library in Central Admin would be fine or we could provision a reporting site to which the farm admin can have full rights.  

Thoughts?

Thank you,

**Comment by tseward** [comment]
Changing the LockType would involve a change in code, but "Job" is the appropriate LockType for this particular solution. The Preferred Server for Timer Jobs would have no impact on where this particular timer job executed. While it is possible to specify a server for a timer job, that is only possible on feature activation. Can I ask why you would want this functionality?

It /may/ be feasible to store a reference to a server name in an object that is outside of this solution, deactivate the feature, then reactivate the feature picking up that name. Can't promise this type of functionality right now, though.

Because we don't know on which server the timer job would execute, the logging path would have to be available on all servers (e.g. C:\reports). You could use a UNC, but that does add complexity to the configuration/administration.

Right now I'm going to go with a Central Admin library. The solution will create the library on your behalf. This configuration will be optional, and it will not create the library if the appropriate setting isn't configured.

**Comment by RumisPoint** [comment]
Let me address reporting first.  Yes, we could have a folder on each WFE called "D:\reports" - I don't see any issues with that.  Do you?  On the other hand, I have no problem with Central Admin library.

Why would I want that functionality?  I think I'm concerned as to the level of load this timer job would put on my production web/app servers.  Not knowing how this timer job will behave, I'm worried it will bog down my servers.  

Thank you,

**Comment by tseward** [comment]
On reporting, no there isn't necessarily an issue with doing that, but I will make the CA Library the priority.

Yep, understood on the performance aspect of it. I will investigate what options are available.

**Comment by RumisPoint** [comment]
Thank you, Trevor.  May I ask if you what your role is in SharePoint - more developer, architect, admin?

**Comment by tseward** [comment]
All 3, but in order: architect, admin, developer.

**Comment by RumisPoint** [comment]
Is it appropriate to ask some questions regarding SharePoint on here or would you rather not?

**Comment by tseward** [comment]
Contact me on my blog - http://thesharepointfarm.com/contact/

**Comment by RumisPoint** [comment]
perfect.  Thank you.

**Comment by tseward** [comment]
Getting back to the logging, I don't think it is possible to grab a list of updated properties, because the solution pulls all properties on each run, much like SharePoint 2013's "AD Import" -- it just scrapes the objects from the domain and pulls everything down.

The exception to this is the Picture, which is compared against current values as that would put a much larger load on the network.

What could be done is a comparison value between properties (what was discovered on that run in Active Directory vs. what SharePoint has), and then logging based on any updated properties. This would be more expensive processing-wise (as there is an additional check). Probably insignificant, though.

**Comment by tseward** [comment]
Take a look at the current release as it addresses a few of these options - https://github.com/Nauplius/FoundationSync/releases/tag/2.52B

**Comment by RumisPoint** [comment]
Trevor,
Thank you for this.  I have not been able to check this due to some other pressing demands.  I have a CAT/QA Foundation 2010 farm on which I will test this and let you know.  Can you kindly summarize what enhancements have been made to the latest release?

Thank you!

**Comment by RumisPoint** [comment]
Never mind, I see all the new features in the wiki.  Very nice!  I can't wait to check this out.  I will keep you posted.

**Comment by tseward** [comment]
Keep in mind that these features are only on the SharePoint 2013 branch. I want to have this branch completed before backporting the changes to 2010 (and not all features may be backported).

**Comment by RumisPoint** [comment]
oh, I see.  So, for 2010 - only the original features will work?

**Comment by tseward** [comment]
Correct, I have not done a code update for SharePoint 2010 yet. I need more feedback on the 2013 beta release as well as improve the logging feature. What I'll likely do is complete the logging feature (with the exception of what properties are updated, that will come later), merge the code into the 2010 solution, then release both as final.

**Comment by RumisPoint** [comment]
Ok, that sounds good.  I do have a SIT 2013 Foundation farm that I can use for this.  I will keep you posted.

**Comment by tseward** [comment]
I've released a 2010 solution, give it a shot in your environment if you can.

https://github.com/Nauplius/FoundationSync/releases/tag/2.6

**Comment by tseward** [comment]
Going to close this one and replace it with a clearer issue.
